def mcxml_version(): ...
def mcxml_add_widget(widget, idNew, idDest): ...
def mcxml_remove_widget(id): ...
def mcxml_measure_text(text, fontSize): ...
def mcxml_select(id): ...
def mcxml_selected(): ...
def mcxml_lastCount(): ...
def mcxml_logFile(value): ...
def mcxml_repeat(ptr): ...
def mcxml_started(ptr): ...
def mcxml_stopped(ptr): ...
def mcxml_loop(xml): ...
def mcxml_exit(): ...
def mcxml_listener_click(ptr): ...
def mcxml_listener_dbclick(ptr): ...
def mcxml_listener_hover(ptr): ...
def mcxml_listener_drag(ptr): ...
def mcxml_listener_keyboard(ptr): ...
def mcxml_listener_resize(ptr): ...
def mcxml_listener_file(ptr): ...
def mcxml_listener_for_list(ptr): ...
def mcxml_listener_for_web(ptr): ...
def mcxml_listener_for_tree(ptr): ...
def mcxml_listener_for_table(ptr): ...
def mcxml_listener_for_check(ptr): ...
def mcxml_listener_for_chart(ptr): ...
def mcxml_listener_for_choice(ptr): ...
def mcxml_set_width(id, value): ...
def mcxml_set_height(id, value): ...
def mcxml_set_widthMin(id, value): ...
def mcxml_set_heightMin(id, value): ...
def mcxml_set_widthMax(id, value): ...
def mcxml_set_heightMax(id, value): ...
def mcxml_set_left(id, value): ...
def mcxml_set_right(id, value): ...
def mcxml_set_top(id, value): ...
def mcxml_set_bottom(id, value): ...
def mcxml_set_center(id, value): ...
def mcxml_set_leftOffset(id, value): ...
def mcxml_set_rightOffset(id, value): ...
def mcxml_set_topOffset(id, value): ...
def mcxml_set_bottomOffset(id, value): ...
def mcxml_set_background(id, value): ...
def mcxml_set_text(id, value): ...
def mcxml_set_hint(id, value): ...
def mcxml_set_textColor(id, value): ...
def mcxml_set_hintColor(id, value): ...
def mcxml_set_textSize(id, value): ...
def mcxml_set_type(id, value): ...
def mcxml_set_visible(id, value): ...
def mcxml_set_fullscreen(id, value): ...
def mcxml_set_maximize(id, value): ...
def mcxml_set_src(id, value): ...
def mcxml_set_actions(id, value): ...
def mcxml_set_autoFit(id, value): ...
def mcxml_set_from(id, value): ...
def mcxml_set_cursor(id, value): ...
def mcxml_set_progress(id, value): ...
def mcxml_set_editable(id, value): ...
def mcxml_set_scroll(id, value): ...
def mcxml_set_pixels(id, value, width, height, depth): ...
def mcxml_set(): ...
def mcxml_get_width(id): ...
def mcxml_get_height(id): ...
def mcxml_get_left(id): ...
def mcxml_get_right(id): ...
def mcxml_get_top(id): ...
def mcxml_get_bottom(id): ...
def mcxml_get_center(id): ...
def mcxml_get_background(id): ...
def mcxml_get_text(id): ...
def mcxml_get_hint(id): ...
def mcxml_get_textColor(id): ...
def mcxml_get_hintColor(id): ...
def mcxml_get_textSize(id): ...
def mcxml_get_type(id): ...
def mcxml_get_visible(id): ...
def mcxml_get_src(id): ...
def mcxml_get_actions(id): ...
def mcxml_get_autoFit(id): ...
def mcxml_get_from(id): ...
def mcxml_get_cursor(id): ...
def mcxml_get_cursor_position(): ...
def mcxml_get_order(id): ...
def mcxml_get_progress(id): ...
def mcxml_get_editable(id): ...
def mcxml_get_scroll(id): ...
def mcxml_get_info(id): ...
def mcxml_set_selection(id, value): ...
def mcxml_set_selectionColor(id, value): ...
def mcxml_get_selection(id): ...
def mcxml_get_selectionColor(id): ...
def mcxml_list_item_add(id, itemIcon, value): ...
def mcxml_list_item_modify_icon(id, itemIcon, pos): ...
def mcxml_list_item_modify_value(id, value, pos): ...
def mcxml_list_item_get(id, pos): ...
def mcxml_list_item_remove(id, pos): ...
def mcxml_list_item_clear(id): ...
def mcxml_list_item_position(id, value): ...
def mcxml_list_item_insert(id, itemIcon, value, pos): ...
def mcxml_list_item_select(id, pos): ...
def mcxml_list_item_selected(id): ...
def mcxml_list_item_count(id): ...
def mcxml_web_find_first(id, value): ...
def mcxml_web_find_last(id, value): ...
def mcxml_web_find_prev(id, value): ...
def mcxml_web_find_next(id, value): ...
def mcxml_tree_item_add(id, itemIcon, value): ...
def mcxml_tree_item_modify_icon(id, itemIcon, pos): ...
def mcxml_tree_item_modify_value(id, value, pos): ...
def mcxml_tree_item_get(id, pos): ...
def mcxml_tree_item_remove(id, pos): ...
def mcxml_tree_item_clear(id): ...
def mcxml_tree_item_position(id, value): ...
def mcxml_tree_item_select(id, pos): ...
def mcxml_tree_item_selected(id): ...
def mcxml_tree_item_count(id): ...
def mcxml_table_item_add(id, itemIcon, value): ...
def mcxml_table_item_modify_icon(id, itemIcon, pos): ...
def mcxml_table_item_modify_value(id, value, pos): ...
def mcxml_table_item_get(id, pos): ...
def mcxml_table_item_remove(id, pos): ...
def mcxml_table_item_clear(id): ...
def mcxml_table_item_position(id, value): ...
def mcxml_table_item_insert(id, itemIcon, value, pos): ...
def mcxml_table_item_select(id, pos): ...
def mcxml_table_item_selected(id): ...
def mcxml_table_item_count(id): ...
def mcxml_check_item_select(id, check): ...
def mcxml_check_item_selected(id): ...
def mcxml_chart_item_add(id, itemIcon, value): ...
def mcxml_chart_item_modify_value(id, value, pos): ...
def mcxml_chart_item_clear(id): ...
def mcxml_chart_item_insert(id, itemIcon, value, pos): ...
def mcxml_chart_item_count(id): ...
def mcxml_chart_item_bounds(id, min, max): ...
def mcxml_choice_item_add(id, itemIcon, value): ...
def mcxml_choice_item_modify_value(id, value, pos): ...
def mcxml_choice_item_get(id, pos): ...
def mcxml_choice_item_remove(id, pos): ...
def mcxml_choice_item_clear(id): ...
def mcxml_choice_item_position(id, value): ...
def mcxml_choice_item_insert(id, itemIcon, value, pos): ...
def mcxml_choice_item_select(id, pos): ...
def mcxml_choice_item_selected(id): ...
def mcxml_choice_item_count(id): ...