/* automatically generated by rust-bindgen 0.70.1 */

/* LVZ */
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(dead_code)]


pub const __MINGW64_VERSION_MAJOR: u32 = 13;
pub const __MINGW64_VERSION_MINOR: u32 = 0;
pub const __MINGW64_VERSION_BUGFIX: u32 = 0;
pub const __MINGW64_VERSION_RC: u32 = 0;
pub const __MINGW64_VERSION_STATE: &[u8; 6] = b"alpha\0";
pub const __MINGW32_MAJOR_VERSION: u32 = 3;
pub const __MINGW32_MINOR_VERSION: u32 = 11;
pub const _M_AMD64: u32 = 100;
pub const _M_X64: u32 = 100;
pub const __: u32 = 1;
pub const __MINGW_USE_UNDERSCORE_PREFIX: u32 = 0;
pub const __MINGW_HAVE_ANSI_C99_PRINTF: u32 = 1;
pub const __MINGW_HAVE_WIDE_C99_PRINTF: u32 = 1;
pub const __MINGW_HAVE_ANSI_C99_SCANF: u32 = 1;
pub const __MINGW_HAVE_WIDE_C99_SCANF: u32 = 1;
pub const __MINGW_SEC_WARN_STR : & [u8 ; 92] = b"This function or variable may be unsafe, use _CRT_SECURE_NO_WARNINGS to disable deprecation\0" ;
pub const __MINGW_MSVC2005_DEPREC_STR : & [u8 ; 117] = b"This POSIX function is deprecated beginning in Visual C++ 2005, use _CRT_NONSTDC_NO_DEPRECATE to disable deprecation\0" ;
pub const __MINGW_FORTIFY_LEVEL: u32 = 0;
pub const __MINGW_FORTIFY_VA_ARG: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY: u32 = 0;
pub const __USE_CRTIMP: u32 = 1;
pub const USE___UUIDOF: u32 = 0;
pub const __CRT__NO_INLINE: u32 = 1;
pub const __MSVCRT_VERSION__: u32 = 3584;
pub const _WIN32_WINNT: u32 = 1539;
pub const MINGW_HAS_SECURE_API: u32 = 1;
pub const __STDC_SECURE_LIB__: u32 = 200411;
pub const __GOT_SECURE_LIB__: u32 = 200411;
pub const MINGW_HAS_DDK_H: u32 = 1;
pub const _CRT_PACKING: u32 = 8;
pub const _SECURECRT_FILL_BUFFER_PATTERN: u32 = 253;
pub const _ARGMAX: u32 = 100;
pub const __USE_MINGW_ANSI_STDIO: u32 = 0;
pub const _CRT_INTERNAL_PRINTF_LEGACY_VSPRINTF_NULL_TERMINATION: u32 = 1;
pub const _CRT_INTERNAL_PRINTF_STANDARD_SNPRINTF_BEHAVIOR: u32 = 2;
pub const _CRT_INTERNAL_PRINTF_LEGACY_WIDE_SPECIFIERS: u32 = 4;
pub const _CRT_INTERNAL_PRINTF_LEGACY_MSVCRT_COMPATIBILITY: u32 = 8;
pub const _CRT_INTERNAL_PRINTF_LEGACY_THREE_DIGIT_EXPONENTS: u32 = 16;
pub const _CRT_INTERNAL_PRINTF_STANDARD_ROUNDING: u32 = 32;
pub const _CRT_INTERNAL_SCANF_SECURECRT: u32 = 1;
pub const _CRT_INTERNAL_SCANF_LEGACY_WIDE_SPECIFIERS: u32 = 2;
pub const _CRT_INTERNAL_SCANF_LEGACY_MSVCRT_COMPATIBILITY: u32 = 4;
pub const _CRT_INTERNAL_LOCAL_PRINTF_OPTIONS: u32 = 36;
pub const _CRT_INTERNAL_LOCAL_SCANF_OPTIONS: u32 = 2;
pub const BUFSIZ: u32 = 512;
pub const _NSTREAM_: u32 = 512;
pub const _IOB_ENTRIES: u32 = 20;
pub const EOF: i32 = -1;
pub const _P_tmpdir: &[u8; 2] = b"\\\0";
pub const _wP_tmpdir: &[u8; 2] = b"\\\0";
pub const L_tmpnam: u32 = 260;
pub const SEEK_CUR: u32 = 1;
pub const SEEK_END: u32 = 2;
pub const SEEK_SET: u32 = 0;
pub const STDIN_FILENO: u32 = 0;
pub const STDOUT_FILENO: u32 = 1;
pub const STDERR_FILENO: u32 = 2;
pub const FILENAME_MAX: u32 = 260;
pub const FOPEN_MAX: u32 = 20;
pub const _SYS_OPEN: u32 = 20;
pub const TMP_MAX: u32 = 2147483647;
pub const _IOFBF: u32 = 0;
pub const _IOLBF: u32 = 64;
pub const _IONBF: u32 = 4;
pub const P_tmpdir: &[u8; 2] = b"\\\0";
pub const SYS_OPEN: u32 = 20;
pub const _P_WAIT: u32 = 0;
pub const _P_NOWAIT: u32 = 1;
pub const _OLD_P_OVERLAY: u32 = 2;
pub const _P_NOWAITO: u32 = 3;
pub const _P_DETACH: u32 = 4;
pub const _P_OVERLAY: u32 = 2;
pub const _WAIT_CHILD: u32 = 0;
pub const _WAIT_GRANDCHILD: u32 = 1;
pub const L_tmpnam_s: u32 = 260;
pub const TMP_MAX_S: u32 = 2147483647;
pub const __bool_true_false_are_defined: u32 = 1;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub type __gnuc_va_list = __builtin_va_list;
pub type va_list = __gnuc_va_list;
extern "C" {
    pub fn __mingw_get_crt_info() -> *const ::std::os::raw::c_char;
}
pub type rsize_t = usize;
pub type wchar_t = ::std::os::raw::c_ushort;
pub type wint_t = ::std::os::raw::c_ushort;
pub type wctype_t = ::std::os::raw::c_ushort;
pub type errno_t = ::std::os::raw::c_int;
pub type __time32_t = ::std::os::raw::c_long;
pub type __time64_t = ::std::os::raw::c_longlong;
pub type time_t = __time64_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct threadmbcinfostruct {
    _unused: [u8; 0],
}
pub type pthreadlocinfo = *mut threadlocaleinfostruct;
pub type pthreadmbcinfo = *mut threadmbcinfostruct;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __lc_time_data {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct localeinfo_struct {
    pub locinfo: pthreadlocinfo,
    pub mbcinfo: pthreadmbcinfo,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of localeinfo_struct"][::std::mem::size_of::<localeinfo_struct>() - 16usize];
    ["Alignment of localeinfo_struct"][::std::mem::align_of::<localeinfo_struct>() - 8usize];
    ["Offset of field: localeinfo_struct::locinfo"]
        [::std::mem::offset_of!(localeinfo_struct, locinfo) - 0usize];
    ["Offset of field: localeinfo_struct::mbcinfo"]
        [::std::mem::offset_of!(localeinfo_struct, mbcinfo) - 8usize];
};
pub type _locale_tstruct = localeinfo_struct;
pub type _locale_t = *mut localeinfo_struct;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tagLC_ID {
    pub wLanguage: ::std::os::raw::c_ushort,
    pub wCountry: ::std::os::raw::c_ushort,
    pub wCodePage: ::std::os::raw::c_ushort,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tagLC_ID"][::std::mem::size_of::<tagLC_ID>() - 6usize];
    ["Alignment of tagLC_ID"][::std::mem::align_of::<tagLC_ID>() - 2usize];
    ["Offset of field: tagLC_ID::wLanguage"][::std::mem::offset_of!(tagLC_ID, wLanguage) - 0usize];
    ["Offset of field: tagLC_ID::wCountry"][::std::mem::offset_of!(tagLC_ID, wCountry) - 2usize];
    ["Offset of field: tagLC_ID::wCodePage"][::std::mem::offset_of!(tagLC_ID, wCodePage) - 4usize];
};
pub type LC_ID = tagLC_ID;
pub type LPLC_ID = *mut tagLC_ID;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct threadlocaleinfostruct {
    pub _locale_pctype: *const ::std::os::raw::c_ushort,
    pub _locale_mb_cur_max: ::std::os::raw::c_int,
    pub _locale_lc_codepage: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of threadlocaleinfostruct"][::std::mem::size_of::<threadlocaleinfostruct>() - 16usize];
    ["Alignment of threadlocaleinfostruct"]
        [::std::mem::align_of::<threadlocaleinfostruct>() - 8usize];
    ["Offset of field: threadlocaleinfostruct::_locale_pctype"]
        [::std::mem::offset_of!(threadlocaleinfostruct, _locale_pctype) - 0usize];
    ["Offset of field: threadlocaleinfostruct::_locale_mb_cur_max"]
        [::std::mem::offset_of!(threadlocaleinfostruct, _locale_mb_cur_max) - 8usize];
    ["Offset of field: threadlocaleinfostruct::_locale_lc_codepage"]
        [::std::mem::offset_of!(threadlocaleinfostruct, _locale_lc_codepage) - 12usize];
};
pub type threadlocinfo = threadlocaleinfostruct;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _iobuf {
    pub _Placeholder: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _iobuf"][::std::mem::size_of::<_iobuf>() - 8usize];
    ["Alignment of _iobuf"][::std::mem::align_of::<_iobuf>() - 8usize];
    ["Offset of field: _iobuf::_Placeholder"]
        [::std::mem::offset_of!(_iobuf, _Placeholder) - 0usize];
};
pub type FILE = _iobuf;
pub type _off_t = ::std::os::raw::c_long;
pub type off32_t = ::std::os::raw::c_long;
pub type _off64_t = ::std::os::raw::c_longlong;
pub type off64_t = ::std::os::raw::c_longlong;
pub type off_t = off32_t;
extern "C" {
    pub fn __acrt_iob_func(index: ::std::os::raw::c_uint) -> *mut FILE;
}
extern "C" {
    pub fn __iob_func() -> *mut FILE;
}
pub type fpos_t = ::std::os::raw::c_longlong;
extern "C" {
    pub fn __mingw_sscanf(
        _Src: *const ::std::os::raw::c_char,
        _Format: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_vsscanf(
        _Str: *const ::std::os::raw::c_char,
        Format: *const ::std::os::raw::c_char,
        argp: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_scanf(_Format: *const ::std::os::raw::c_char, ...) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_vscanf(
        Format: *const ::std::os::raw::c_char,
        argp: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_fscanf(
        _File: *mut FILE,
        _Format: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_vfscanf(
        fp: *mut FILE,
        Format: *const ::std::os::raw::c_char,
        argp: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_vsnprintf(
        _DstBuf: *mut ::std::os::raw::c_char,
        _MaxCount: usize,
        _Format: *const ::std::os::raw::c_char,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_snprintf(
        s: *mut ::std::os::raw::c_char,
        n: usize,
        format: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_printf(arg1: *const ::std::os::raw::c_char, ...) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_vprintf(
        arg1: *const ::std::os::raw::c_char,
        arg2: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_fprintf(
        arg1: *mut FILE,
        arg2: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_vfprintf(
        arg1: *mut FILE,
        arg2: *const ::std::os::raw::c_char,
        arg3: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_sprintf(
        arg1: *mut ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_vsprintf(
        arg1: *mut ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        arg3: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_asprintf(
        arg1: *mut *mut ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_vasprintf(
        arg1: *mut *mut ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        arg3: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_sscanf(
        _Src: *const ::std::os::raw::c_char,
        _Format: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_scanf(_Format: *const ::std::os::raw::c_char, ...) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_fscanf(
        _File: *mut FILE,
        _Format: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_printf(arg1: *const ::std::os::raw::c_char, ...) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_vprintf(
        arg1: *const ::std::os::raw::c_char,
        arg2: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_fprintf(
        arg1: *mut FILE,
        arg2: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_vfprintf(
        arg1: *mut FILE,
        arg2: *const ::std::os::raw::c_char,
        arg3: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_sprintf(
        arg1: *mut ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_vsprintf(
        arg1: *mut ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        arg3: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __stdio_common_vsprintf(
        options: ::std::os::raw::c_ulonglong,
        str_: *mut ::std::os::raw::c_char,
        len: usize,
        format: *const ::std::os::raw::c_char,
        locale: _locale_t,
        valist: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __stdio_common_vfprintf(
        options: ::std::os::raw::c_ulonglong,
        file: *mut FILE,
        format: *const ::std::os::raw::c_char,
        locale: _locale_t,
        valist: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __stdio_common_vsscanf(
        options: ::std::os::raw::c_ulonglong,
        input: *const ::std::os::raw::c_char,
        length: usize,
        format: *const ::std::os::raw::c_char,
        locale: _locale_t,
        valist: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __stdio_common_vfscanf(
        options: ::std::os::raw::c_ulonglong,
        file: *mut FILE,
        format: *const ::std::os::raw::c_char,
        locale: _locale_t,
        valist: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fprintf(
        _File: *mut FILE,
        _Format: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn printf(_Format: *const ::std::os::raw::c_char, ...) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn sprintf(
        _Dest: *mut ::std::os::raw::c_char,
        _Format: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn vfprintf(
        _File: *mut FILE,
        _Format: *const ::std::os::raw::c_char,
        _ArgList: __builtin_va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn vprintf(
        _Format: *const ::std::os::raw::c_char,
        _ArgList: __builtin_va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn vsprintf(
        _Dest: *mut ::std::os::raw::c_char,
        _Format: *const ::std::os::raw::c_char,
        _Args: __builtin_va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fscanf(
        _File: *mut FILE,
        _Format: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn scanf(_Format: *const ::std::os::raw::c_char, ...) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn sscanf(
        _Src: *const ::std::os::raw::c_char,
        _Format: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn vfscanf(
        __stream: *mut FILE,
        __format: *const ::std::os::raw::c_char,
        __local_argv: __builtin_va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn vsscanf(
        __source: *const ::std::os::raw::c_char,
        __format: *const ::std::os::raw::c_char,
        __local_argv: __builtin_va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn vscanf(
        __format: *const ::std::os::raw::c_char,
        __local_argv: __builtin_va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _filbuf(_File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _flsbuf(_Ch: ::std::os::raw::c_int, _File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _fsopen(
        _Filename: *const ::std::os::raw::c_char,
        _Mode: *const ::std::os::raw::c_char,
        _ShFlag: ::std::os::raw::c_int,
    ) -> *mut FILE;
}
extern "C" {
    pub fn clearerr(_File: *mut FILE);
}
extern "C" {
    pub fn fclose(_File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _fcloseall() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _fdopen(
        _FileHandle: ::std::os::raw::c_int,
        _Mode: *const ::std::os::raw::c_char,
    ) -> *mut FILE;
}
extern "C" {
    pub fn feof(_File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ferror(_File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fflush(_File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fgetc(_File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _fgetchar() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fgetpos(_File: *mut FILE, _Pos: *mut fpos_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fgetpos64(_File: *mut FILE, _Pos: *mut fpos_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fgets(
        _Buf: *mut ::std::os::raw::c_char,
        _MaxCount: ::std::os::raw::c_int,
        _File: *mut FILE,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn _fileno(_File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _tempnam(
        _DirName: *const ::std::os::raw::c_char,
        _FilePrefix: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn _flushall() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fopen(
        _Filename: *const ::std::os::raw::c_char,
        _Mode: *const ::std::os::raw::c_char,
    ) -> *mut FILE;
}
extern "C" {
    pub fn fopen64(
        filename: *const ::std::os::raw::c_char,
        mode: *const ::std::os::raw::c_char,
    ) -> *mut FILE;
}
extern "C" {
    pub fn fputc(_Ch: ::std::os::raw::c_int, _File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _fputchar(_Ch: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fputs(_Str: *const ::std::os::raw::c_char, _File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fread(
        _DstBuf: *mut ::std::os::raw::c_void,
        _ElementSize: ::std::os::raw::c_ulonglong,
        _Count: ::std::os::raw::c_ulonglong,
        _File: *mut FILE,
    ) -> ::std::os::raw::c_ulonglong;
}
extern "C" {
    pub fn freopen(
        _Filename: *const ::std::os::raw::c_char,
        _Mode: *const ::std::os::raw::c_char,
        _File: *mut FILE,
    ) -> *mut FILE;
}
extern "C" {
    pub fn fsetpos(_File: *mut FILE, _Pos: *const fpos_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fsetpos64(_File: *mut FILE, _Pos: *const fpos_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fseek(
        _File: *mut FILE,
        _Offset: ::std::os::raw::c_long,
        _Origin: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ftell(_File: *mut FILE) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn _fseeki64(
        _File: *mut FILE,
        _Offset: ::std::os::raw::c_longlong,
        _Origin: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _ftelli64(_File: *mut FILE) -> ::std::os::raw::c_longlong;
}
extern "C" {
    pub fn fwrite(
        _Str: *const ::std::os::raw::c_void,
        _Size: ::std::os::raw::c_ulonglong,
        _Count: ::std::os::raw::c_ulonglong,
        _File: *mut FILE,
    ) -> ::std::os::raw::c_ulonglong;
}
extern "C" {
    pub fn getc(_File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn getchar() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _getmaxstdio() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn gets(_Buffer: *mut ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn _getw(_File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn perror(_ErrMsg: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn _pclose(_File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _popen(
        _Command: *const ::std::os::raw::c_char,
        _Mode: *const ::std::os::raw::c_char,
    ) -> *mut FILE;
}
extern "C" {
    pub fn putc(_Ch: ::std::os::raw::c_int, _File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn putchar(_Ch: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn puts(_Str: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _putw(_Word: ::std::os::raw::c_int, _File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn remove(_Filename: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rename(
        _OldFilename: *const ::std::os::raw::c_char,
        _NewFilename: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _unlink(_Filename: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn unlink(_Filename: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rewind(_File: *mut FILE);
}
extern "C" {
    pub fn _rmtmp() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn setbuf(_File: *mut FILE, _Buffer: *mut ::std::os::raw::c_char);
}
extern "C" {
    pub fn _setmaxstdio(_Max: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _set_output_format(_Format: ::std::os::raw::c_uint) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn _get_output_format() -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn setvbuf(
        _File: *mut FILE,
        _Buf: *mut ::std::os::raw::c_char,
        _Mode: ::std::os::raw::c_int,
        _Size: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _scprintf(_Format: *const ::std::os::raw::c_char, ...) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _snscanf(
        _Src: *const ::std::os::raw::c_char,
        _MaxCount: usize,
        _Format: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _vscprintf(
        _Format: *const ::std::os::raw::c_char,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tmpfile() -> *mut FILE;
}
extern "C" {
    pub fn tmpnam(_Buffer: *mut ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn ungetc(_Ch: ::std::os::raw::c_int, _File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _vsnprintf(
        _Dest: *mut ::std::os::raw::c_char,
        _Count: usize,
        _Format: *const ::std::os::raw::c_char,
        _Args: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _snprintf(
        _Dest: *mut ::std::os::raw::c_char,
        _Count: usize,
        _Format: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn vsnprintf(
        __stream: *mut ::std::os::raw::c_char,
        __n: ::std::os::raw::c_ulonglong,
        __format: *const ::std::os::raw::c_char,
        __local_argv: __builtin_va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn snprintf(
        __stream: *mut ::std::os::raw::c_char,
        __n: ::std::os::raw::c_ulonglong,
        __format: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _set_printf_count_output(_Value: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _get_printf_count_output() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_swscanf(
        _Src: *const wchar_t,
        _Format: *const wchar_t,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_vswscanf(
        _Str: *const wchar_t,
        Format: *const wchar_t,
        argp: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_wscanf(_Format: *const wchar_t, ...) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_vwscanf(Format: *const wchar_t, argp: va_list) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_fwscanf(_File: *mut FILE, _Format: *const wchar_t, ...)
        -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_vfwscanf(
        fp: *mut FILE,
        Format: *const wchar_t,
        argp: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_fwprintf(
        _File: *mut FILE,
        _Format: *const wchar_t,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_wprintf(_Format: *const wchar_t, ...) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_vfwprintf(
        _File: *mut FILE,
        _Format: *const wchar_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_vwprintf(_Format: *const wchar_t, _ArgList: va_list) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_snwprintf(
        s: *mut wchar_t,
        n: usize,
        format: *const wchar_t,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_vsnwprintf(
        arg1: *mut wchar_t,
        arg2: usize,
        arg3: *const wchar_t,
        arg4: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_swprintf(arg1: *mut wchar_t, arg2: *const wchar_t, ...)
        -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_vswprintf(
        arg1: *mut wchar_t,
        arg2: *const wchar_t,
        arg3: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_swscanf(
        _Src: *const wchar_t,
        _Format: *const wchar_t,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_wscanf(_Format: *const wchar_t, ...) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_fwscanf(_File: *mut FILE, _Format: *const wchar_t, ...) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_fwprintf(_File: *mut FILE, _Format: *const wchar_t, ...) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_wprintf(_Format: *const wchar_t, ...) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_vfwprintf(
        _File: *mut FILE,
        _Format: *const wchar_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_vwprintf(_Format: *const wchar_t, _ArgList: va_list) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_swprintf(arg1: *mut wchar_t, arg2: *const wchar_t, ...) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __ms_vswprintf(
        arg1: *mut wchar_t,
        arg2: *const wchar_t,
        arg3: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __stdio_common_vswprintf(
        options: ::std::os::raw::c_ulonglong,
        str_: *mut wchar_t,
        len: usize,
        format: *const wchar_t,
        locale: _locale_t,
        valist: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __stdio_common_vfwprintf(
        options: ::std::os::raw::c_ulonglong,
        file: *mut FILE,
        format: *const wchar_t,
        locale: _locale_t,
        valist: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __stdio_common_vswscanf(
        options: ::std::os::raw::c_ulonglong,
        input: *const wchar_t,
        length: usize,
        format: *const wchar_t,
        locale: _locale_t,
        valist: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __stdio_common_vfwscanf(
        options: ::std::os::raw::c_ulonglong,
        file: *mut FILE,
        format: *const wchar_t,
        locale: _locale_t,
        valist: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fwprintf(_File: *mut FILE, _Format: *const wchar_t, ...) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _wfsopen(
        _Filename: *const wchar_t,
        _Mode: *const wchar_t,
        _ShFlag: ::std::os::raw::c_int,
    ) -> *mut FILE;
}
extern "C" {
    pub fn fgetwc(_File: *mut FILE) -> wint_t;
}
extern "C" {
    pub fn _fgetwchar() -> wint_t;
}
extern "C" {
    pub fn fputwc(_Ch: wchar_t, _File: *mut FILE) -> wint_t;
}
extern "C" {
    pub fn _fputwchar(_Ch: wchar_t) -> wint_t;
}
extern "C" {
    pub fn getwc(_File: *mut FILE) -> wint_t;
}
extern "C" {
    pub fn getwchar() -> wint_t;
}
extern "C" {
    pub fn putwc(_Ch: wchar_t, _File: *mut FILE) -> wint_t;
}
extern "C" {
    pub fn putwchar(_Ch: wchar_t) -> wint_t;
}
extern "C" {
    pub fn ungetwc(_Ch: wint_t, _File: *mut FILE) -> wint_t;
}
extern "C" {
    pub fn fgetws(
        _Dst: *mut wchar_t,
        _SizeInWords: ::std::os::raw::c_int,
        _File: *mut FILE,
    ) -> *mut wchar_t;
}
extern "C" {
    pub fn fputws(_Str: *const wchar_t, _File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _getws(_String: *mut wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn _putws(_Str: *const wchar_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _snwprintf(
        _Dest: *mut wchar_t,
        _Count: usize,
        _Format: *const wchar_t,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _vsnwprintf(
        _Dest: *mut wchar_t,
        _Count: usize,
        _Format: *const wchar_t,
        _Args: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _wtempnam(_Directory: *const wchar_t, _FilePrefix: *const wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn _snwscanf(
        _Src: *const wchar_t,
        _MaxCount: usize,
        _Format: *const wchar_t,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _wfdopen(_FileHandle: ::std::os::raw::c_int, _Mode: *const wchar_t) -> *mut FILE;
}
extern "C" {
    pub fn _wfopen(_Filename: *const wchar_t, _Mode: *const wchar_t) -> *mut FILE;
}
extern "C" {
    pub fn _wfreopen(
        _Filename: *const wchar_t,
        _Mode: *const wchar_t,
        _OldFile: *mut FILE,
    ) -> *mut FILE;
}
extern "C" {
    pub fn _wperror(_ErrMsg: *const wchar_t);
}
extern "C" {
    pub fn _wpopen(_Command: *const wchar_t, _Mode: *const wchar_t) -> *mut FILE;
}
extern "C" {
    pub fn _wremove(_Filename: *const wchar_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _wtmpnam(_Buffer: *mut wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn _fgetwc_nolock(_File: *mut FILE) -> wint_t;
}
extern "C" {
    pub fn _fputwc_nolock(_Ch: wchar_t, _File: *mut FILE) -> wint_t;
}
extern "C" {
    pub fn _ungetwc_nolock(_Ch: wint_t, _File: *mut FILE) -> wint_t;
}
extern "C" {
    pub fn _fgetc_nolock(_File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _fputc_nolock(_Char: ::std::os::raw::c_int, _File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _getc_nolock(_File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _putc_nolock(_Char: ::std::os::raw::c_int, _File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _lock_file(_File: *mut FILE);
}
extern "C" {
    pub fn _unlock_file(_File: *mut FILE);
}
extern "C" {
    pub fn _fclose_nolock(_File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _fflush_nolock(_File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _fread_nolock(
        _DstBuf: *mut ::std::os::raw::c_void,
        _ElementSize: usize,
        _Count: usize,
        _File: *mut FILE,
    ) -> usize;
}
extern "C" {
    pub fn _fseek_nolock(
        _File: *mut FILE,
        _Offset: ::std::os::raw::c_long,
        _Origin: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _ftell_nolock(_File: *mut FILE) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn _fseeki64_nolock(
        _File: *mut FILE,
        _Offset: ::std::os::raw::c_longlong,
        _Origin: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _ftelli64_nolock(_File: *mut FILE) -> ::std::os::raw::c_longlong;
}
extern "C" {
    pub fn _fwrite_nolock(
        _DstBuf: *const ::std::os::raw::c_void,
        _Size: usize,
        _Count: usize,
        _File: *mut FILE,
    ) -> usize;
}
extern "C" {
    pub fn _ungetc_nolock(_Ch: ::std::os::raw::c_int, _File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tempnam(
        _Directory: *const ::std::os::raw::c_char,
        _FilePrefix: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn fcloseall() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fdopen(
        _FileHandle: ::std::os::raw::c_int,
        _Format: *const ::std::os::raw::c_char,
    ) -> *mut FILE;
}
extern "C" {
    pub fn fgetchar() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fileno(_File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn flushall() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fputchar(_Ch: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn getw(_File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn putw(_Ch: ::std::os::raw::c_int, _File: *mut FILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rmtmp() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_str_wide_utf8(
        wptr: *const wchar_t,
        mbptr: *mut *mut ::std::os::raw::c_char,
        buflen: *mut usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_str_utf8_wide(
        mbptr: *const ::std::os::raw::c_char,
        wptr: *mut *mut wchar_t,
        buflen: *mut usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __mingw_str_free(ptr: *mut ::std::os::raw::c_void);
}
extern "C" {
    pub fn _wspawnl(
        _Mode: ::std::os::raw::c_int,
        _Filename: *const wchar_t,
        _ArgList: *const wchar_t,
        ...
    ) -> isize;
}
extern "C" {
    pub fn _wspawnle(
        _Mode: ::std::os::raw::c_int,
        _Filename: *const wchar_t,
        _ArgList: *const wchar_t,
        ...
    ) -> isize;
}
extern "C" {
    pub fn _wspawnlp(
        _Mode: ::std::os::raw::c_int,
        _Filename: *const wchar_t,
        _ArgList: *const wchar_t,
        ...
    ) -> isize;
}
extern "C" {
    pub fn _wspawnlpe(
        _Mode: ::std::os::raw::c_int,
        _Filename: *const wchar_t,
        _ArgList: *const wchar_t,
        ...
    ) -> isize;
}
extern "C" {
    pub fn _wspawnv(
        _Mode: ::std::os::raw::c_int,
        _Filename: *const wchar_t,
        _ArgList: *const *const wchar_t,
    ) -> isize;
}
extern "C" {
    pub fn _wspawnve(
        _Mode: ::std::os::raw::c_int,
        _Filename: *const wchar_t,
        _ArgList: *const *const wchar_t,
        _Env: *const *const wchar_t,
    ) -> isize;
}
extern "C" {
    pub fn _wspawnvp(
        _Mode: ::std::os::raw::c_int,
        _Filename: *const wchar_t,
        _ArgList: *const *const wchar_t,
    ) -> isize;
}
extern "C" {
    pub fn _wspawnvpe(
        _Mode: ::std::os::raw::c_int,
        _Filename: *const wchar_t,
        _ArgList: *const *const wchar_t,
        _Env: *const *const wchar_t,
    ) -> isize;
}
extern "C" {
    pub fn _spawnv(
        _Mode: ::std::os::raw::c_int,
        _Filename: *const ::std::os::raw::c_char,
        _ArgList: *const *const ::std::os::raw::c_char,
    ) -> isize;
}
extern "C" {
    pub fn _spawnve(
        _Mode: ::std::os::raw::c_int,
        _Filename: *const ::std::os::raw::c_char,
        _ArgList: *const *const ::std::os::raw::c_char,
        _Env: *const *const ::std::os::raw::c_char,
    ) -> isize;
}
extern "C" {
    pub fn _spawnvp(
        _Mode: ::std::os::raw::c_int,
        _Filename: *const ::std::os::raw::c_char,
        _ArgList: *const *const ::std::os::raw::c_char,
    ) -> isize;
}
extern "C" {
    pub fn _spawnvpe(
        _Mode: ::std::os::raw::c_int,
        _Filename: *const ::std::os::raw::c_char,
        _ArgList: *const *const ::std::os::raw::c_char,
        _Env: *const *const ::std::os::raw::c_char,
    ) -> isize;
}
extern "C" {
    pub fn clearerr_s(_File: *mut FILE) -> errno_t;
}
extern "C" {
    pub fn fread_s(
        _DstBuf: *mut ::std::os::raw::c_void,
        _DstSize: usize,
        _ElementSize: usize,
        _Count: usize,
        _File: *mut FILE,
    ) -> usize;
}
extern "C" {
    pub fn __stdio_common_vsprintf_s(
        _Options: ::std::os::raw::c_ulonglong,
        _Str: *mut ::std::os::raw::c_char,
        _Len: usize,
        _Format: *const ::std::os::raw::c_char,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __stdio_common_vsprintf_p(
        _Options: ::std::os::raw::c_ulonglong,
        _Str: *mut ::std::os::raw::c_char,
        _Len: usize,
        _Format: *const ::std::os::raw::c_char,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __stdio_common_vsnprintf_s(
        _Options: ::std::os::raw::c_ulonglong,
        _Str: *mut ::std::os::raw::c_char,
        _Len: usize,
        _MaxCount: usize,
        _Format: *const ::std::os::raw::c_char,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __stdio_common_vfprintf_s(
        _Options: ::std::os::raw::c_ulonglong,
        _File: *mut FILE,
        _Format: *const ::std::os::raw::c_char,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __stdio_common_vfprintf_p(
        _Options: ::std::os::raw::c_ulonglong,
        _File: *mut FILE,
        _Format: *const ::std::os::raw::c_char,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fopen_s(
        _File: *mut *mut FILE,
        _Filename: *const ::std::os::raw::c_char,
        _Mode: *const ::std::os::raw::c_char,
    ) -> errno_t;
}
extern "C" {
    pub fn freopen_s(
        _File: *mut *mut FILE,
        _Filename: *const ::std::os::raw::c_char,
        _Mode: *const ::std::os::raw::c_char,
        _Stream: *mut FILE,
    ) -> errno_t;
}
extern "C" {
    pub fn gets_s(arg1: *mut ::std::os::raw::c_char, arg2: rsize_t) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn tmpfile_s(_File: *mut *mut FILE) -> errno_t;
}
extern "C" {
    pub fn tmpnam_s(arg1: *mut ::std::os::raw::c_char, arg2: rsize_t) -> errno_t;
}
extern "C" {
    pub fn _getws_s(_Str: *mut wchar_t, _SizeInWords: usize) -> *mut wchar_t;
}
extern "C" {
    pub fn __stdio_common_vswprintf_s(
        _Options: ::std::os::raw::c_ulonglong,
        _Str: *mut wchar_t,
        _Len: usize,
        _Format: *const wchar_t,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __stdio_common_vsnwprintf_s(
        _Options: ::std::os::raw::c_ulonglong,
        _Str: *mut wchar_t,
        _Len: usize,
        _MaxCount: usize,
        _Format: *const wchar_t,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __stdio_common_vfwprintf_s(
        _Options: ::std::os::raw::c_ulonglong,
        _File: *mut FILE,
        _Format: *const wchar_t,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _wfopen_s(
        _File: *mut *mut FILE,
        _Filename: *const wchar_t,
        _Mode: *const wchar_t,
    ) -> errno_t;
}
extern "C" {
    pub fn _wfreopen_s(
        _File: *mut *mut FILE,
        _Filename: *const wchar_t,
        _Mode: *const wchar_t,
        _OldFile: *mut FILE,
    ) -> errno_t;
}
extern "C" {
    pub fn _wtmpnam_s(_DstBuf: *mut wchar_t, _SizeInWords: usize) -> errno_t;
}
extern "C" {
    pub fn _fread_nolock_s(
        _DstBuf: *mut ::std::os::raw::c_void,
        _DstSize: usize,
        _ElementSize: usize,
        _Count: usize,
        _File: *mut FILE,
    ) -> usize;
}
extern "C" {
    #[doc = " @brief Get the version of this library.\n @return Library version."]
    pub fn mcxml_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Add a new widget.\n @param widget The widget type to add.\n @param idNew A unique id to identify the widget.\n @param idDest The id of App or the id of any Scroll widget.\n @return SUCCESS_FAILURE"]
    pub fn mcxml_add_widget(
        widget: *const ::std::os::raw::c_char,
        idNew: *const ::std::os::raw::c_char,
        idDest: *const ::std::os::raw::c_char,
    ) -> bool;
}
extern "C" {
    #[doc = " @brief Remove a widget.\n @param id THE_ID_WIDGET\n @return SUCCESS_FAILURE"]
    pub fn mcxml_remove_widget(id: *const ::std::os::raw::c_char) -> bool;
}
extern "C" {
    #[doc = " @brief Get the width and height of a text.\n @param text The text to be measured.\n @param fontSize Measure at a particular font size.\n @return The width and height obtained."]
    pub fn mcxml_measure_text(
        text: *const ::std::os::raw::c_char,
        fontSize: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Select a widget.\n @param id THE_ID_BOTH"]
    pub fn mcxml_select(id: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " @brief Get the selected widget.\n @return The selected widget."]
    pub fn mcxml_selected() -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief If 'int*' is returned by any function, mcxml_lastCount will hold its size.\n @return A size."]
    pub fn mcxml_lastCount() -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Output errors to a file."]
    pub fn mcxml_logFile(value: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " @brief Pass a function to be called every N seconds. Cancel with nullptr.\n @param ptr A function to call.\n @param sec interval before a call."]
    pub fn mcxml_repeat(ptr: ::std::option::Option<unsafe extern "C" fn()>, sec: f32);
}
extern "C" {
    #[doc = " @brief Pass a function to be called every N seconds. Cancel with nullptr.\n @param ptr A function to call.\n @param sec interval before a call."]
    pub fn mcxml_started(ptr: ::std::option::Option<unsafe extern "C" fn()>);
}
extern "C" {
    #[doc = " @brief Pass a function to be called every N seconds. Cancel with nullptr.\n @param ptr A function to call.\n @param sec interval before a call."]
    pub fn mcxml_stopped(ptr: ::std::option::Option<unsafe extern "C" fn()>);
}
extern "C" {
    #[doc = " @brief Start the app.\n @param xml XML/MCXML to run.\n @return SUCCESS_FAILURE"]
    pub fn mcxml_loop(xml: *const ::std::os::raw::c_char) -> bool;
}
extern "C" {
    #[doc = " @brief Close the app."]
    pub fn mcxml_exit();
}
extern "C" {
    #[doc = " @brief Called when any listening widget is clicked.\n A click widget listener can be set in the xml/mcxml with <span class='code'>actions=\"click\"</span>\n @param ptr FUNCTON_IN_THE_FORM"]
    pub fn mcxml_listener_click(
        ptr: ::std::option::Option<
            unsafe extern "C" fn(
                id: *const ::std::os::raw::c_char,
                m: *const ::std::os::raw::c_char,
            ),
        >,
    );
}
extern "C" {
    #[doc = " @brief Called when any listening widget is double clicked.\n A double click widget listener can be set in the xml/mcxml with <span class='code'>actions=\"dbclick\"</span>\n @param ptr FUNCTON_IN_THE_FORM"]
    pub fn mcxml_listener_dbclick(
        ptr: ::std::option::Option<
            unsafe extern "C" fn(
                id: *const ::std::os::raw::c_char,
                m: *const ::std::os::raw::c_char,
            ),
        >,
    );
}
extern "C" {
    #[doc = " @brief Called when any listening widget is hovered.\n A hover widget listener can be set in the xml/mcxml with <span class='code'>actions=\"hover\"</span>\n @param ptr FUNCTON_IN_THE_FORM"]
    pub fn mcxml_listener_hover(
        ptr: ::std::option::Option<
            unsafe extern "C" fn(
                id: *const ::std::os::raw::c_char,
                m: *const ::std::os::raw::c_char,
            ),
        >,
    );
}
extern "C" {
    #[doc = " @brief Called when any listening widget is dragged.\n A drag widget listener can be set in the xml/mcxml with <span class='code'>actions=\"drag\"</span>\n @param ptr FUNCTON_IN_THE_FORM"]
    pub fn mcxml_listener_drag(
        ptr: ::std::option::Option<
            unsafe extern "C" fn(
                id: *const ::std::os::raw::c_char,
                m: *const ::std::os::raw::c_char,
            ),
        >,
    );
}
extern "C" {
    #[doc = " @brief When this global listener is set, all key events will be directed to it.\n @param ptr FUNCTON_IN_THE_FORM"]
    pub fn mcxml_listener_keyboard(
        ptr: ::std::option::Option<
            unsafe extern "C" fn(
                id: *const ::std::os::raw::c_char,
                m: *const ::std::os::raw::c_char,
            ),
        >,
    );
}
extern "C" {
    #[doc = " @brief When this global listener is set, any App resize will be directed to it.\n @param ptr FUNCTON_IN_THE_FORM"]
    pub fn mcxml_listener_resize(
        ptr: ::std::option::Option<
            unsafe extern "C" fn(
                id: *const ::std::os::raw::c_char,
                m: *const ::std::os::raw::c_char,
            ),
        >,
    );
}
extern "C" {
    #[doc = " @brief Called when a file is dragged from a File Browser into any listening widget.\n A file widget listener can be set in the xml/mcxml with <span class='code'>actions=\"file\"</span>\n @param ptr FUNCTON_IN_THE_FORM"]
    pub fn mcxml_listener_file(
        ptr: ::std::option::Option<
            unsafe extern "C" fn(
                id: *const ::std::os::raw::c_char,
                m: *const ::std::os::raw::c_char,
            ),
        >,
    );
}
extern "C" {
    #[doc = " @brief Called when any List widget is interacted with.\n @param ptr FUNCTON_IN_THE_FORM"]
    pub fn mcxml_listener_for_list(
        ptr: ::std::option::Option<
            unsafe extern "C" fn(
                id: *const ::std::os::raw::c_char,
                m: *const ::std::os::raw::c_char,
            ),
        >,
    );
}
extern "C" {
    #[doc = " @brief Called when any List widget is interacted with.\n @param ptr FUNCTON_IN_THE_FORM"]
    pub fn mcxml_listener_for_web(
        ptr: ::std::option::Option<
            unsafe extern "C" fn(
                id: *const ::std::os::raw::c_char,
                m: *const ::std::os::raw::c_char,
            ),
        >,
    );
}
extern "C" {
    #[doc = " @brief Called when any List widget is interacted with.\n @param ptr FUNCTON_IN_THE_FORM"]
    pub fn mcxml_listener_for_tree(
        ptr: ::std::option::Option<
            unsafe extern "C" fn(
                id: *const ::std::os::raw::c_char,
                m: *const ::std::os::raw::c_char,
            ),
        >,
    );
}
extern "C" {
    #[doc = " @brief Called when any List widget is interacted with.\n @param ptr FUNCTON_IN_THE_FORM"]
    pub fn mcxml_listener_for_table(
        ptr: ::std::option::Option<
            unsafe extern "C" fn(
                id: *const ::std::os::raw::c_char,
                m: *const ::std::os::raw::c_char,
            ),
        >,
    );
}
extern "C" {
    #[doc = " @brief Called when any List widget is interacted with.\n @param ptr FUNCTON_IN_THE_FORM"]
    pub fn mcxml_listener_for_check(
        ptr: ::std::option::Option<
            unsafe extern "C" fn(
                id: *const ::std::os::raw::c_char,
                m: *const ::std::os::raw::c_char,
            ),
        >,
    );
}
extern "C" {
    #[doc = " @brief Called when any List widget is interacted with.\n @param ptr FUNCTON_IN_THE_FORM"]
    pub fn mcxml_listener_for_chart(
        ptr: ::std::option::Option<
            unsafe extern "C" fn(
                id: *const ::std::os::raw::c_char,
                m: *const ::std::os::raw::c_char,
            ),
        >,
    );
}
extern "C" {
    #[doc = " @brief Called when any List widget is interacted with.\n @param ptr FUNCTON_IN_THE_FORM"]
    pub fn mcxml_listener_for_choice(
        ptr: ::std::option::Option<
            unsafe extern "C" fn(
                id: *const ::std::os::raw::c_char,
                m: *const ::std::os::raw::c_char,
            ),
        >,
    );
}
extern "C" {
    #[doc = " @brief Set the width of a widget or App.\n @param id THE_ID_BOTH\n @param value THE_VALUE"]
    pub fn mcxml_set_width(id: *const ::std::os::raw::c_char, value: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " @brief Set the height of a widget or App.\n @param id THE_ID_BOTH\n @param value THE_VALUE"]
    pub fn mcxml_set_height(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the width of App.\n @param id THE_ID_APP\n @param value THE_VALUE  SUPPORTS_BAR_SEP_NOT"]
    pub fn mcxml_set_widthMin(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the height of App.\n @param id THE_ID_APP\n @param value THE_VALUE  SUPPORTS_BAR_SEP_NOT"]
    pub fn mcxml_set_heightMin(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the width of App.\n @param id THE_ID_APP\n @param value THE_VALUE  SUPPORTS_BAR_SEP_NOT"]
    pub fn mcxml_set_widthMax(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the height of App.\n @param id THE_ID_APP\n @param value THE_VALUE  SUPPORTS_BAR_SEP_NOT"]
    pub fn mcxml_set_heightMax(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the left position of a widget.\n @param id THE_ID_WIDGET\n @param value THE_VALUE"]
    pub fn mcxml_set_left(id: *const ::std::os::raw::c_char, value: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " @brief Set the right position of a widget.\n @param id THE_ID_WIDGET\n @param value THE_VALUE"]
    pub fn mcxml_set_right(id: *const ::std::os::raw::c_char, value: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " @brief Set the top position of a widget.\n @param id THE_ID_WIDGET\n @param value THE_VALUE"]
    pub fn mcxml_set_top(id: *const ::std::os::raw::c_char, value: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " @brief Set the bottom position of a widget.\n @param id THE_ID_WIDGET\n @param value THE_VALUE"]
    pub fn mcxml_set_bottom(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the center position of a widget.\n @param id THE_ID_WIDGET\n @param value THE_VALUE"]
    pub fn mcxml_set_center(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the left offset of a widget.\n SET_WHEN 'left' is set.\n @param id THE_ID_WIDGET\n @param value THE_VALUE"]
    pub fn mcxml_set_leftOffset(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the right offset of a widget.\n SET_WHEN 'right' is set.\n @param id THE_ID_WIDGET\n @param value THE_VALUE"]
    pub fn mcxml_set_rightOffset(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the top offset of a widget.\n SET_WHEN 'top' is set.\n @param id THE_ID_WIDGET\n @param value THE_VALUE"]
    pub fn mcxml_set_topOffset(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the bottom offset of a widget.\n SET_WHEN 'bottom' is set.\n @param id THE_ID_WIDGET\n @param value THE_VALUE"]
    pub fn mcxml_set_bottomOffset(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the background color of a widget or App.\n @param id THE_ID_BOTH\n @param value THE_VALUE"]
    pub fn mcxml_set_background(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the text of a widget or the title of App.\n @param id THE_ID_BOTH\n @param value THE_VALUE"]
    pub fn mcxml_set_text(id: *const ::std::os::raw::c_char, value: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " @brief Set the hint of a widget.\n @param id THE_ID_WIDGET\n @param value THE_VALUE"]
    pub fn mcxml_set_hint(id: *const ::std::os::raw::c_char, value: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " @brief Set the text color of a widget.\n @param id THE_ID_WIDGET\n @param value THE_VALUE  SUPPORTS_BAR_SEP"]
    pub fn mcxml_set_textColor(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the hint color of a widget.\n @param id THE_ID_WIDGET\n @param value THE_VALUE  SUPPORTS_BAR_SEP"]
    pub fn mcxml_set_hintColor(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the text size of a widget.\n @param id THE_ID_WIDGET\n @param value THE_VALUE"]
    pub fn mcxml_set_textSize(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the input type of Input.\n @param id THE_ID\n @param value THE_VALUE"]
    pub fn mcxml_set_type(id: *const ::std::os::raw::c_char, value: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " @brief Set the visibility of a widget.\n @param id THE_ID_WIDGET\n @param value THE_VALUE"]
    pub fn mcxml_set_visible(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Make App fullscreen.\n @param id THE_ID_APP\n @param value THE_VALUE"]
    pub fn mcxml_set_fullscreen(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Make App maximized.\n @param id THE_ID_APP\n @param value THE_VALUE"]
    pub fn mcxml_set_maximize(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the image of Image.\n @param id THE_ID\n @param value THE_VALUE  SUPPORTS_BAR_SEP"]
    pub fn mcxml_set_src(id: *const ::std::os::raw::c_char, value: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " @brief Set listeners on a widget.\n @param id THE_ID_WIDGET\n @param value THE_VALUE  SUPPORTS_BAR_SEP"]
    pub fn mcxml_set_actions(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the auto fit of a widget.\n @param id THE_ID_WIDGET\n @param value THE_VALUE"]
    pub fn mcxml_set_autoFit(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Use attributes of another widget as basis.\n @param id THE_ID_WIDGET\n @param value THE_VALUE"]
    pub fn mcxml_set_from(id: *const ::std::os::raw::c_char, value: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " @brief Set the cursor type of a widget or App.\n @param id THE_ID_BOTH\n @param value THE_VALUE  Available values: insert, hand, drag, ew (i.e. East-West), ns (i.e. North-South), ne (i.e. North-East), sw (i.e. South-West), nw (i.e. North-West), se (i.e. South-East)."]
    pub fn mcxml_set_cursor(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the cursor type of a widget or App.\n @param id THE_ID_BOTH\n @param value THE_VALUE  Available values: insert, hand, drag, ew (i.e. East-West), ns (i.e. North-South), ne (i.e. North-East), sw (i.e. South-West), nw (i.e. North-West), se (i.e. South-East)."]
    pub fn mcxml_set_progress(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the cursor type of a widget or App.\n @param id THE_ID_BOTH\n @param value THE_VALUE  Available values: insert, hand, drag, ew (i.e. East-West), ns (i.e. North-South), ne (i.e. North-East), sw (i.e. South-West), nw (i.e. North-West), se (i.e. South-East)."]
    pub fn mcxml_set_editable(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the cursor type of a widget or App.\n @param id THE_ID_BOTH\n @param value THE_VALUE  Available values: insert, hand, drag, ew (i.e. East-West), ns (i.e. North-South), ne (i.e. North-East), sw (i.e. South-West), nw (i.e. North-West), se (i.e. South-East)."]
    pub fn mcxml_set_pixels(
        id: *const ::std::os::raw::c_char,
        value: *mut ::std::os::raw::c_uchar,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        depth: ::std::os::raw::c_int,
    );
}
extern "C" {
    #[doc = " @brief Set the cursor type of a widget or App.\n @param id THE_ID_BOTH\n @param value THE_VALUE  Available values: insert, hand, drag, ew (i.e. East-West), ns (i.e. North-South), ne (i.e. North-East), sw (i.e. South-West), nw (i.e. North-West), se (i.e. South-East)."]
    pub fn mcxml_set_scroll(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Commit modifications made."]
    pub fn mcxml_set();
}
extern "C" {
    #[doc = " @brief Get the width of a widget or App.\n @param id THE_ID_BOTH\n @return The width set to a widget or App."]
    pub fn mcxml_get_width(id: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the height of a widget or App.\n @param id THE_ID_BOTH\n @return The height set to a widget or App."]
    pub fn mcxml_get_height(id: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the left of a widget or App.\n @param id THE_ID_BOTH\n @return The left set to a widget or App."]
    pub fn mcxml_get_left(id: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the right of a widget or App.\n @param id THE_ID_BOTH\n @return The right set to a widget or App."]
    pub fn mcxml_get_right(id: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the top of a widget or App.\n @param id THE_ID_BOTH\n @return The top set to a widget or App."]
    pub fn mcxml_get_top(id: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the bottom of a widget or App.\n @param id THE_ID_BOTH\n @return The bottom set to a widget or App."]
    pub fn mcxml_get_bottom(id: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the center of a widget or App.\n @param id THE_ID_BOTH\n @return The center set to a widget or App."]
    pub fn mcxml_get_center(id: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the background color of a widget or App.\n @param id THE_ID_BOTH\n @return The background color set to a widget or App."]
    pub fn mcxml_get_background(id: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the text of a widget or the title of App.\n @param id THE_ID_BOTH\n @return The text set to a widget or the title of App."]
    pub fn mcxml_get_text(id: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the hint of a widget.\n @param id THE_ID_WIDGET\n @return The hint set to a widget."]
    pub fn mcxml_get_hint(id: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the text color of a widget.\n @param id THE_ID_WIDGET\n @return The text color set to a widget. SUPPORTS_BAR_SEP"]
    pub fn mcxml_get_textColor(id: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the hint color of a widget.\n @param id THE_ID_WIDGET\n @return The hint color set to a widget. SUPPORTS_BAR_SEP"]
    pub fn mcxml_get_hintColor(id: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the text size of a widget.\n @param id THE_ID_WIDGET\n @return The text size set to a widget."]
    pub fn mcxml_get_textSize(id: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the input type of Input.\n @param id THE_ID\n @return The input type set to Input."]
    pub fn mcxml_get_type(id: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the visibility of a widget.\n @param id THE_ID_WIDGET\n @return The visibility set to a widget."]
    pub fn mcxml_get_visible(id: *const ::std::os::raw::c_char) -> bool;
}
extern "C" {
    #[doc = " @brief Get the image/images of Image.\n @param id THE_ID\n @return Images set to Image. SUPPORTS_BAR_SEP"]
    pub fn mcxml_get_src(id: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get listeners of a widget.\n @param id THE_ID_WIDGET\n @return Widget listeners of a widget or an empty string if there is no action set."]
    pub fn mcxml_get_actions(id: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the auto fit of a widget.\n @param id THE_ID_WIDGET\n @return The auto fit set to a widget."]
    pub fn mcxml_get_autoFit(id: *const ::std::os::raw::c_char) -> bool;
}
extern "C" {
    #[doc = " @brief Get the ID of the widget used for the basis of a widget.\n @param id THE_ID_WIDGET\n @return The id set to a widget."]
    pub fn mcxml_get_from(id: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the cursor type of a widget or App.\n @param id THE_ID_BOTH\n @return The cursor type set to a widget or App."]
    pub fn mcxml_get_cursor(id: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the position of the cursor.\n @return The positon of the cursor."]
    pub fn mcxml_get_cursor_position() -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the position of the cursor.\n @return The positon of the cursor."]
    pub fn mcxml_get_order(id: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the position of the cursor.\n @return The positon of the cursor."]
    pub fn mcxml_get_progress(id: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the position of the cursor.\n @return The positon of the cursor."]
    pub fn mcxml_get_editable(id: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the position of the cursor.\n @return The positon of the cursor."]
    pub fn mcxml_get_info(id: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the position of the cursor.\n @return The positon of the cursor."]
    pub fn mcxml_get_scroll(id: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Set insert position or selection.\n @param id THE_ID\n @param value THE_VALUE"]
    pub fn mcxml_set_selection(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Set the selection color of Input or Editor.\n @param id THE_ID\n @param value THE_VALUE"]
    pub fn mcxml_set_selectionColor(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Get insert position or selection.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_get_selection(id: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_get_selectionColor(
        id: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_list_item_add(
        id: *const ::std::os::raw::c_char,
        itemIcon: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_list_item_modify_icon(
        id: *const ::std::os::raw::c_char,
        itemIcon: *const ::std::os::raw::c_char,
        pos: ::std::os::raw::c_int,
    );
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_list_item_modify_value(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
        pos: ::std::os::raw::c_int,
    );
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_list_item_get(
        id: *const ::std::os::raw::c_char,
        pos: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_list_item_remove(id: *const ::std::os::raw::c_char, pos: ::std::os::raw::c_int);
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_list_item_clear(id: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_list_item_position(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_list_item_insert(
        id: *const ::std::os::raw::c_char,
        itemIcon: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
        pos: ::std::os::raw::c_int,
    );
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_list_item_select(id: *const ::std::os::raw::c_char, pos: ::std::os::raw::c_int);
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_list_item_selected(
        id: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_list_item_count(id: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_web_find_first(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> bool;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_web_find_last(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> bool;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_web_find_prev(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> bool;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_web_find_next(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> bool;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_tree_item_add(
        id: *const ::std::os::raw::c_char,
        itemIcon: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_tree_item_modify_icon(
        id: *const ::std::os::raw::c_char,
        itemIcon: *const ::std::os::raw::c_char,
        pos: ::std::os::raw::c_int,
    );
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_tree_item_modify_value(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
        pos: ::std::os::raw::c_int,
    );
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_tree_item_get(
        id: *const ::std::os::raw::c_char,
        pos: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_tree_item_remove(id: *const ::std::os::raw::c_char, pos: ::std::os::raw::c_int);
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_tree_item_clear(id: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_tree_item_position(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_tree_item_select(id: *const ::std::os::raw::c_char, pos: ::std::os::raw::c_int);
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_tree_item_selected(
        id: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_tree_item_count(id: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_table_item_add(
        id: *const ::std::os::raw::c_char,
        itemIcon: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_table_item_modify_icon(
        id: *const ::std::os::raw::c_char,
        itemIcon: *const ::std::os::raw::c_char,
        pos: ::std::os::raw::c_int,
    );
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_table_item_modify_value(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
        pos: ::std::os::raw::c_int,
    );
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_table_item_get(
        id: *const ::std::os::raw::c_char,
        pos: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_table_item_remove(id: *const ::std::os::raw::c_char, pos: ::std::os::raw::c_int);
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_table_item_clear(id: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_table_item_position(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_table_item_insert(
        id: *const ::std::os::raw::c_char,
        itemIcon: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
        pos: ::std::os::raw::c_int,
    );
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_table_item_select(id: *const ::std::os::raw::c_char, pos: ::std::os::raw::c_int);
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_table_item_selected(
        id: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_table_item_count(id: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_check_item_select(id: *const ::std::os::raw::c_char, check: bool);
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_check_item_selected(id: *const ::std::os::raw::c_char) -> bool;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_chart_item_add(
        id: *const ::std::os::raw::c_char,
        itemIcon: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_chart_item_modify_value(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
        pos: ::std::os::raw::c_int,
    );
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_chart_item_clear(id: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_chart_item_insert(
        id: *const ::std::os::raw::c_char,
        itemIcon: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
        pos: ::std::os::raw::c_int,
    );
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_chart_item_count(id: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_chart_item_bounds(id: *const ::std::os::raw::c_char, min: f64, max: f64);
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_choice_item_add(
        id: *const ::std::os::raw::c_char,
        itemIcon: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_choice_item_modify_value(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
        pos: ::std::os::raw::c_int,
    );
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_choice_item_get(
        id: *const ::std::os::raw::c_char,
        pos: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_choice_item_remove(id: *const ::std::os::raw::c_char, pos: ::std::os::raw::c_int);
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_choice_item_clear(id: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_choice_item_position(
        id: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_choice_item_insert(
        id: *const ::std::os::raw::c_char,
        itemIcon: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
        pos: ::std::os::raw::c_int,
    );
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_choice_item_select(id: *const ::std::os::raw::c_char, pos: ::std::os::raw::c_int);
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_choice_item_selected(
        id: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Get the selection color of Input or Editor.\n @param id THE_ID\n @return THE_VALUE"]
    pub fn mcxml_choice_item_count(id: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
pub type __builtin_va_list = *mut ::std::os::raw::c_char;
