const char* mcxml_version();
bool mcxml_add_widget(const char* widget, const char* idNew, const char* idDest);
bool mcxml_remove_widget(const char* id);
const char* mcxml_measure_text(const char* text, int fontSize);
void mcxml_select(const char* id);
const char* mcxml_selected();
int mcxml_lastCount();
void mcxml_logFile(const char* value);
void mcxml_repeat(void (*ptr);
void mcxml_started(void (*ptr);
void mcxml_stopped(void (*ptr);
bool mcxml_loop(const char* xml);
void mcxml_exit();
void mcxml_listener_click(void (*ptr);
void mcxml_listener_dbclick(void (*ptr);
void mcxml_listener_hover(void (*ptr);
void mcxml_listener_drag(void (*ptr);
void mcxml_listener_keyboard(void (*ptr);
void mcxml_listener_resize(void (*ptr);
void mcxml_listener_file(void (*ptr);
void mcxml_listener_for_list(void (*ptr);
void mcxml_listener_for_web(void (*ptr);
void mcxml_listener_for_tree(void (*ptr);
void mcxml_listener_for_table(void (*ptr);
void mcxml_listener_for_check(void (*ptr);
void mcxml_listener_for_chart(void (*ptr);
void mcxml_listener_for_choice(void (*ptr);
void mcxml_set_width(const char* id, const char* value);
void mcxml_set_height(const char* id, const char* value);
void mcxml_set_widthMin(const char* id, const char* value);
void mcxml_set_heightMin(const char* id, const char* value);
void mcxml_set_widthMax(const char* id, const char* value);
void mcxml_set_heightMax(const char* id, const char* value);
void mcxml_set_left(const char* id, const char* value);
void mcxml_set_right(const char* id, const char* value);
void mcxml_set_top(const char* id, const char* value);
void mcxml_set_bottom(const char* id, const char* value);
void mcxml_set_center(const char* id, const char* value);
void mcxml_set_leftOffset(const char* id, const char* value);
void mcxml_set_rightOffset(const char* id, const char* value);
void mcxml_set_topOffset(const char* id, const char* value);
void mcxml_set_bottomOffset(const char* id, const char* value);
void mcxml_set_background(const char* id, const char* value);
void mcxml_set_text(const char* id, const char* value);
void mcxml_set_hint(const char* id, const char* value);
void mcxml_set_textColor(const char* id, const char* value);
void mcxml_set_hintColor(const char* id, const char* value);
void mcxml_set_textSize(const char* id, const char* value);
void mcxml_set_type(const char* id, const char* value);
void mcxml_set_visible(const char* id, const char* value);
void mcxml_set_fullscreen(const char* id, const char* value);
void mcxml_set_maximize(const char* id, const char* value);
void mcxml_set_src(const char* id, const char* value);
void mcxml_set_actions(const char* id, const char* value);
void mcxml_set_autoFit(const char* id, const char* value);
void mcxml_set_from(const char* id, const char* value);
void mcxml_set_cursor(const char* id, const char* value);
void mcxml_set_progress(const char* id, const char* value);
void mcxml_set_editable(const char* id, const char* value);
void mcxml_set_pixels(const char* id, unsigned char* value, int width, int height, int depth);
void mcxml_set_scroll(const char* id, const char* value);
void mcxml_set();
int mcxml_get_width(const char* id);
int mcxml_get_height(const char* id);
int mcxml_get_left(const char* id);
int mcxml_get_right(const char* id);
int mcxml_get_top(const char* id);
int mcxml_get_bottom(const char* id);
const char* mcxml_get_center(const char* id);
int mcxml_get_background(const char* id);
const char* mcxml_get_text(const char* id);
const char* mcxml_get_hint(const char* id);
const char* mcxml_get_textColor(const char* id);
const char* mcxml_get_hintColor(const char* id);
int mcxml_get_textSize(const char* id);
const char* mcxml_get_type(const char* id);
bool mcxml_get_visible(const char* id);
const char* mcxml_get_src(const char* id);
const char* mcxml_get_actions(const char* id);
bool mcxml_get_autoFit(const char* id);
const char* mcxml_get_from(const char* id);
const char* mcxml_get_cursor(const char* id);
const char* mcxml_get_cursor_position();
const char* mcxml_get_order(const char* id);
const char* mcxml_get_progress(const char* id);
const char* mcxml_get_editable(const char* id);
const char* mcxml_get_info(const char* id);
const char* mcxml_get_scroll(const char* id);
void mcxml_set_selection(const char* id, const char* value);
void mcxml_set_selectionColor(const char* id, const char* value);
const char* mcxml_get_selection(const char* id);
const char* mcxml_get_selectionColor(const char* id);
void mcxml_list_item_add(const char* id, const char* itemIcon, const char* value);
void mcxml_list_item_modify_icon(const char* id, const char* itemIcon, int pos);
void mcxml_list_item_modify_value(const char* id, const char* value, int pos);
const char* mcxml_list_item_get(const char* id, int pos);
void mcxml_list_item_remove(const char* id, int pos);
void mcxml_list_item_clear(const char* id);
int mcxml_list_item_position(const char* id, const char* value);
void mcxml_list_item_insert(const char* id, const char* itemIcon, const char* value, int pos);
void mcxml_list_item_select(const char* id, int pos);
int* mcxml_list_item_selected(const char* id);
int mcxml_list_item_count(const char* id);
bool mcxml_web_find_first(const char* id, const char* value);
bool mcxml_web_find_last(const char* id, const char* value);
bool mcxml_web_find_prev(const char* id, const char* value);
bool mcxml_web_find_next(const char* id, const char* value);
void mcxml_tree_item_add(const char* id, const char* itemIcon, const char* value);
void mcxml_tree_item_modify_icon(const char* id, const char* itemIcon, int pos);
void mcxml_tree_item_modify_value(const char* id, const char* value, int pos);
const char* mcxml_tree_item_get(const char* id, int pos);
void mcxml_tree_item_remove(const char* id, int pos);
void mcxml_tree_item_clear(const char* id);
int mcxml_tree_item_position(const char* id, const char* value);
void mcxml_tree_item_select(const char* id, int pos);
int* mcxml_tree_item_selected(const char* id);
int mcxml_tree_item_count(const char* id);
void mcxml_table_item_add(const char* id, const char* itemIcon, const char* value);
void mcxml_table_item_modify_icon(const char* id, const char* itemIcon, int pos);
void mcxml_table_item_modify_value(const char* id, const char* value, int pos);
const char* mcxml_table_item_get(const char* id, int pos);
void mcxml_table_item_remove(const char* id, int pos);
void mcxml_table_item_clear(const char* id);
int mcxml_table_item_position(const char* id, const char* value);
void mcxml_table_item_insert(const char* id, const char* itemIcon, const char* value, int pos);
void mcxml_table_item_select(const char* id, int pos);
int* mcxml_table_item_selected(const char* id);
int mcxml_table_item_count(const char* id);
void mcxml_check_item_select(const char* id, bool check);
bool mcxml_check_item_selected(const char* id);
void mcxml_chart_item_add(const char* id, const char* itemIcon, const char* value);
void mcxml_chart_item_modify_value(const char* id, const char* value, int pos);
void mcxml_chart_item_clear(const char* id);
void mcxml_chart_item_insert(const char* id, const char* itemIcon, const char* value, int pos);
int mcxml_chart_item_count(const char* id);
void mcxml_chart_item_bounds(const char* id, double min, double max);
void mcxml_choice_item_add(const char* id, const char* itemIcon, const char* value);
void mcxml_choice_item_modify_value(const char* id, const char* value, int pos);
const char* mcxml_choice_item_get(const char* id, int pos);
void mcxml_choice_item_remove(const char* id, int pos);
void mcxml_choice_item_clear(const char* id);
int mcxml_choice_item_position(const char* id, const char* value);
void mcxml_choice_item_insert(const char* id, const char* itemIcon, const char* value, int pos);
void mcxml_choice_item_select(const char* id, int pos);
int* mcxml_choice_item_selected(const char* id);
int mcxml_choice_item_count(const char* id);